{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "github-pr-controller.fullname" . }}-manager-role
rules:
- apiGroups:
  - github.colossyan.com
  resources:
  - pullrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - github.colossyan.com
  resources:
  - pullrequests/finalizers
  verbs:
  - update
- apiGroups:
  - github.colossyan.com
  resources:
  - pullrequests/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - github.colossyan.com
  resources:
  - repositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - github.colossyan.com
  resources:
  - repositories/finalizers
  verbs:
  - update
- apiGroups:
  - github.colossyan.com
  resources:
  - repositories/status
  verbs:
  - get
  - patch
  - update
{{- end }}