name: Push
on:
  push:
    branches:
      - master
    tags:
      - "v?[0-9]+.[0-9]+.[0-9]+"
env:
  PLATFORMS: linux/amd64
jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Determine tag or commit
        uses: haya14busa/action-cond@v1
        id: refortag
        with:
          cond: ${{ startsWith(github.ref, 'refs/tags/') }}
          if_true: ${{ github.ref }}
          if_false: latest
      - name: Determine image tag
        id: imagetag
        env:
          TAG_OR_BRANCH: ${{ steps.refortag.outputs.value }}
        run: echo "::set-output name=value::${TAG_OR_BRANCH##*/}"
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build kafka-operator
        uses: docker/build-push-action@v2
        with:
          tags: ghcr.io/adamantal/github-pr-controller:${{ steps.imagetag.outputs.value }}
          file: Dockerfile
          push: true
